name = "lapce-discord-rpc"
version = "0.0.0"
author = "jodev7"
display-name = "Discord Presence"
description = "Lapce plugin to connect to Discord"
wasm = "bin/discord-rpc.wasm"
icon = 'icons/logo.png'
repository = "https://github.com/jodev7/lapce-discord-presence"

[activation]
language = []
workspace-contains = []

[config."volt.serverPath"]
default = ""
description = "Path to custom LSP executable"

# [config."volt.serverArgs"]
# default = []
# description = ""

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
